name: Continuous Deployment

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Read Frontend and Backend Version Files
        id: versions
        run: |
          FRONTEND_VERSION=$(cat frontend/VERSION | tr -d '\r')
          BACKEND_VERSION=$(cat backend/VERSION | tr -d '\r')
          echo "FRONTEND_VERSION=${FRONTEND_VERSION}" >> $GITHUB_ENV
          echo "BACKEND_VERSION=${BACKEND_VERSION}" >> $GITHUB_ENV

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t ghcr.io/mateszombati/s2retro/frontend:${FRONTEND_VERSION} ./frontend
          docker push ghcr.io/mateszombati/s2retro/frontend:${FRONTEND_VERSION}

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ghcr.io/mateszombati/s2retro/backend:${BACKEND_VERSION} ./backend
          docker push ghcr.io/mateszombati/s2retro/backend:${BACKEND_VERSION}

      - name: Create and Push Git Tags for Frontend and Backend Versions
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          git tag frontend-v${FRONTEND_VERSION}
          git tag backend-v${BACKEND_VERSION}
          
          git push origin frontend-v${FRONTEND_VERSION}
          git push origin backend-v${BACKEND_VERSION}